##################
### jsp set
##################
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db?autoReconnect=true&amp;useUnicode=true&amp;charaterEncoding=utf-8
    username: root
    password: root
  
##################
### log set
##################
logging:
  file: /var/log/spring-boot.log
  level.*: INFO
  level.com.security: DEBUG
  
##################
### server set
##################
server:
  context-path: /
  port: 8082
  session:
    timeout: 1800
    
##################
### mybatis set
##################
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: cn.blmdz.wechat.model
  
##################
### other set
##################
other:
  debugger: false
